<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="../css_folder/teacher_lessons.css">

    <!-- bootstrap link -->
    <link rel="stylesheet" href="../bootstrap_folder/css/bootstrap.min.css">

    <!-- font awesome cdn link -->
    <link rel="stylesheet" href="../font-awesome-icon/css/all.min.css">
</head>

<body>

    <div class="container-fluid p-0">
        <nav>
            <div class="nav-logo">
                <a href="/learning_management/public/?url=teacher_class&id=<?= $subject_id ?>&grade_id=<?= $grade_level_id ?>">
                    <i class="fa fa-arrow-left"></i>
                </a>
            </div>

            <div class="nav-menu">
                <button>
                    <i class="fa fa-bars"></i>
                </button>
            </div>
        </nav>

        <main>
            <div class="card-parent-box">
                <div class="card-header">
                    <h3>Content</h3>

                    <!-- Only "Modules" button at the top level.
                         Lesson / Video / Image / Activity buttons now live
                         INSIDE each module card (generated by lesson.js). -->
                    <div class="buttons">
                        <button type="button" id="addModuleBtn">
                            <i class="fa fa-file"></i>
                            Modules
                        </button>
                    </div>
                </div>

                <form action="?url=upload" method="post">

                    <div id="contentContainer">
                        <div class="text-content">
                            <i class="fa fa-circle-question"></i>
                            <p>No Content</p>
                        </div>
                    </div>

                </form>

                <div class="card-footer">
                    <h3>Additional Materials (Optional)</h3>

                    <div class="card-materials">
                        <i class="fa fa-arrow-up-from-bracket"></i>
                        <p>Upload supplementary materials</p>
                        <span>PDF, Powerpoint, Word Document (max 50MB)</span>
                        <input type="file" name="materials[]" multiple>
                    </div>
                </div>

                <div class="card-submit">
                    <button type="button">Cancel</button>
                    <button type="submit">Save Lessons</button>
                </div>
            </div>
        </main>
    </div>

    <!-- bootstrap link javascript -->
    <script defer src="../bootstrap_folder/js/bootstrap.bundle.min.js"></script>

    <script src="../teacher_folder/lesson_folder/lesson.js"></script>
</body>

</html>